# permissions for end users to edit boundarypkiworkers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: boundarypkiworker-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: boundary-worker-operator
    app.kubernetes.io/part-of: boundary-worker-operator
    app.kubernetes.io/managed-by: kustomize
  name: boundarypkiworker-editor-role
rules:
- apiGroups:
  - workers.boundaryproject.io
  resources:
  - boundarypkiworkers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workers.boundaryproject.io
  resources:
  - boundarypkiworkers/status
  verbs:
  - get
