//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoundaryPKIWorker) DeepCopyInto(out *BoundaryPKIWorker) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoundaryPKIWorker.
func (in *BoundaryPKIWorker) DeepCopy() *BoundaryPKIWorker {
	if in == nil {
		return nil
	}
	out := new(BoundaryPKIWorker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BoundaryPKIWorker) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoundaryPKIWorkerList) DeepCopyInto(out *BoundaryPKIWorkerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BoundaryPKIWorker, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoundaryPKIWorkerList.
func (in *BoundaryPKIWorkerList) DeepCopy() *BoundaryPKIWorkerList {
	if in == nil {
		return nil
	}
	out := new(BoundaryPKIWorkerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BoundaryPKIWorkerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoundaryPKIWorkerRegistrationSpec) DeepCopyInto(out *BoundaryPKIWorkerRegistrationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoundaryPKIWorkerRegistrationSpec.
func (in *BoundaryPKIWorkerRegistrationSpec) DeepCopy() *BoundaryPKIWorkerRegistrationSpec {
	if in == nil {
		return nil
	}
	out := new(BoundaryPKIWorkerRegistrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoundaryPKIWorkerSpec) DeepCopyInto(out *BoundaryPKIWorkerSpec) {
	*out = *in
	out.Registration = in.Registration
	out.Storage = in.Storage
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoundaryPKIWorkerSpec.
func (in *BoundaryPKIWorkerSpec) DeepCopy() *BoundaryPKIWorkerSpec {
	if in == nil {
		return nil
	}
	out := new(BoundaryPKIWorkerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoundaryPKIWorkerStatus) DeepCopyInto(out *BoundaryPKIWorkerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoundaryPKIWorkerStatus.
func (in *BoundaryPKIWorkerStatus) DeepCopy() *BoundaryPKIWorkerStatus {
	if in == nil {
		return nil
	}
	out := new(BoundaryPKIWorkerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoundaryPKIWorkerStorageSpec) DeepCopyInto(out *BoundaryPKIWorkerStorageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoundaryPKIWorkerStorageSpec.
func (in *BoundaryPKIWorkerStorageSpec) DeepCopy() *BoundaryPKIWorkerStorageSpec {
	if in == nil {
		return nil
	}
	out := new(BoundaryPKIWorkerStorageSpec)
	in.DeepCopyInto(out)
	return out
}
